# Generated by Django 2.2.14 on 2022-01-04 12:29

from django.db import migrations, models
import django.db.models.deletion
import main.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProductUtils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Price of the product', max_digits=10)),
                ('quantity', models.IntegerField(default=0, help_text='Quantity of the product')),
                ('rate', models.DecimalField(decimal_places=2, default=0, help_text='The rate of the product, can see if the product is liked or not', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Description, describes the details of the product', null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the theme', max_length=16)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='connected',
            field=models.DateTimeField(blank=True, help_text='The last connection date, used to check timeout of token', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, help_text='Auto-set on login via the interface and cleaned on logout', max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('modelproductutils_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.ModelProductUtils')),
                ('title', models.CharField(help_text='Title of the manga', max_length=64)),
                ('volume', models.IntegerField(help_text='The volume number')),
                ('author', models.CharField(help_text='Author of the manga', max_length=32)),
                ('release', models.DateTimeField(help_text='This is the release date for reference')),
                ('category', models.CharField(choices=[('shonen', 'Shonen'), ('shojo', 'Shojo'), ('seinen', 'Seinen'), ('josei', 'Josei'), ('yaoi', 'Yaoi'), ('yuri', 'Yuri')], default='shonen', help_text='This define the mangas category', max_length=16)),
                ('picture', models.FileField(blank=True, default=None, help_text='Either set a file here', null=True, upload_to=main.utils.models.rename_file)),
                ('themes', models.ManyToManyField(blank=True, help_text='Differents themes of the mangas', to='main.Theme')),
            ],
            bases=('main.modelproductutils',),
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(help_text='Total price in the user shopping cart', null=True)),
                ('user', models.ForeignKey(help_text='User linked to this ShoppingCart', on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('shopping_cart', models.ForeignKey(help_text='ShoppingCart', on_delete=django.db.models.deletion.CASCADE, to='main.ShoppingCart')),
                ('manga', models.ForeignKey(help_text='Manga we wanted to buy', on_delete=django.db.models.deletion.CASCADE, to='main.Manga')),
            ],
        ),
    ]
