# Generated by Django 2.2.14 on 2022-01-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220104_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='release',
            field=models.IntegerField(help_text='This is the release year for reference'),
        ),
    ]
