# Generated by Django 2.2.14 on 2022-01-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220104_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingitem',
            name='number',
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
