# Generated by Django 2.2.14 on 2022-01-06 20:54

from django.db import migrations, models
import django.db.models.deletion
import main.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220104_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figurine',
            fields=[
                ('modelproductutils_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.ModelProductUtils')),
                ('name', models.CharField(help_text='Name of the Figurine', max_length=64)),
                ('collection', models.CharField(help_text='Name of the figurine collection', max_length=32)),
                ('picture', models.FileField(blank=True, default=None, help_text='Either set a file here', null=True, upload_to=main.utils.models.rename_file)),
            ],
            bases=('main.modelproductutils',),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='manga',
            field=models.ForeignKey(help_text='Manga we wanted to buy', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Manga'),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='figurine',
            field=models.ForeignKey(help_text='Figurine we wanted to buy', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Figurine'),
        ),
    ]
